version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/dnsscaling
    environment:
      TZ: "/usr/share/zoneinfo/America/Los_Angeles"
    steps:
      - checkout
      # install miniconda
      - run: wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - run: bash Miniconda3-latest-Linux-x86_64.sh -b
      # install environment
      - run: ${HOME}/miniconda3/bin/conda update --yes --quiet conda conda-env
      - run: ${HOME}/miniconda3/bin/conda env create -n test_env -f environment.yml
      # run tests
      - run: source ${HOME}/miniconda3/bin/activate test_env && py.test --cov-report xml:coverage.xml --cov dnssclaing --verbose

